package triforce;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author l147033
 */
public class Cadastrar_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_Cliente
     */
    public Cadastrar_Cliente() {
        initComponents();
        lbl_confirmar_nome.setVisible(false);
        lbl_confirmar_nome.setForeground(Color.red);
        lbl_confirmar_cpf.setVisible(false);
        lbl_confirmar_cpf.setForeground(Color.red);
        lbl_confirmar_telefone.setVisible(false);
        lbl_confirmar_telefone.setForeground(Color.red);
        lbl_confirmar_email.setVisible(false);
        lbl_confirmar_email.setForeground(Color.red);
        lbl_confirmar_endereco.setVisible(false);
        lbl_confirmar_endereco.setForeground(Color.red);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbn_titulo = new javax.swing.JLabel();
        lbn_nome = new javax.swing.JLabel();
        lbn_cpf = new javax.swing.JLabel();
        lbn_telefone = new javax.swing.JLabel();
        lbn_email = new javax.swing.JLabel();
        lbn_endereco = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        lbl_campo_obrigatorio = new javax.swing.JLabel();
        lbl_confirmar_nome = new javax.swing.JLabel();
        lbl_confirmar_cpf = new javax.swing.JLabel();
        lbl_confirmar_telefone = new javax.swing.JLabel();
        lbl_confirmar_email = new javax.swing.JLabel();
        lbl_confirmar_endereco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbn_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbn_titulo.setText("Cadastrar Cliente");

        lbn_nome.setText("Nome*");

        lbn_cpf.setText("CPF*");

        lbn_telefone.setText("Telefone*");

        lbn_email.setText("E-mail*");

        lbn_endereco.setText("Endereço*");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setPreferredSize(new java.awt.Dimension(80, 25));
        btn_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseClicked(evt);
            }
        });
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.setPreferredSize(new java.awt.Dimension(80, 25));

        lbl_campo_obrigatorio.setText("*campos obrigátorios");

        lbl_confirmar_nome.setText("*");

        lbl_confirmar_cpf.setText("*");

        lbl_confirmar_telefone.setText("*");

        lbl_confirmar_email.setText("*");

        lbl_confirmar_endereco.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_campo_obrigatorio)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbn_titulo)
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbn_cpf)
                    .addComponent(lbn_nome)
                    .addComponent(lbn_telefone)
                    .addComponent(lbn_email)
                    .addComponent(lbn_endereco))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_cpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_telefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_confirmar_nome)
                    .addComponent(lbl_confirmar_cpf)
                    .addComponent(lbl_confirmar_telefone)
                    .addComponent(lbl_confirmar_email)
                    .addComponent(lbl_confirmar_endereco))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lbl_campo_obrigatorio)
                .addGap(18, 18, 18)
                .addComponent(lbn_titulo)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbn_nome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_confirmar_nome)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbn_cpf)
                            .addComponent(lbl_confirmar_cpf))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbn_telefone)
                            .addComponent(lbl_confirmar_telefone))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbn_email)
                    .addComponent(lbl_confirmar_email))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbn_endereco)
                    .addComponent(lbl_confirmar_endereco))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseClicked
        // TODO add your handling code here:
        //nome
        if (txt_nome.getText().length() > 0)
        {
            lbl_confirmar_nome.setVisible(false);
            
        }else
        {
            lbl_confirmar_nome.setVisible(true);
            
        }
        //cpf
        if(txt_cpf.getText().length() > 0 )
        {
            lbl_confirmar_cpf.setVisible(false);
        }else{
            lbl_confirmar_cpf.setVisible(true);
        }
       //telefone
        if(txt_telefone.getText().length()>0)
        {
            lbl_confirmar_telefone.setVisible(false);
        }else{
            lbl_confirmar_telefone.setVisible(true);
        }
        //email
        if(txt_email.getText().length() > 0 )
        {
            lbl_confirmar_email.setVisible(false);
        }else{
            lbl_confirmar_email.setVisible(true);
        }
        //endereço
        if(txt_endereco.getText().length() > 0)
        {
            lbl_confirmar_endereco.setVisible(false);
        }else{
            lbl_confirmar_endereco.setVisible(true);
        }
        //// fim dos if encadeados 
        
        if(txt_nome.getText().length() > 0 
           && txt_cpf.getText().length()> 0 
           && txt_telefone.getText().length() > 0 
           && txt_email.getText().length() > 0 
           && txt_endereco.getText().length() > 0)          
        {
        JOptionPane.showMessageDialog(null, "Dados cadastrados com Sucesso");        
        }
        else{
       // JOptionPane.showMessageDialog(null, "Favor validar" );
        }
    }//GEN-LAST:event_btn_cadastrarMouseClicked

    
    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lbl_campo_obrigatorio;
    private javax.swing.JLabel lbl_confirmar_cpf;
    private javax.swing.JLabel lbl_confirmar_email;
    private javax.swing.JLabel lbl_confirmar_endereco;
    private javax.swing.JLabel lbl_confirmar_nome;
    private javax.swing.JLabel lbl_confirmar_telefone;
    private javax.swing.JLabel lbn_cpf;
    private javax.swing.JLabel lbn_email;
    private javax.swing.JLabel lbn_endereco;
    private javax.swing.JLabel lbn_nome;
    private javax.swing.JLabel lbn_telefone;
    private javax.swing.JLabel lbn_titulo;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
