package triforce;


import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a145292
 */
public class CadastroReserva extends javax.swing.JFrame {

    /**
     * Creates new form CadastroReserva
     */
    public CadastroReserva() {
        initComponents();
        lbl_confirmarDataLcto.setVisible(false);
        lbl_confirmarDataLcto.setForeground(Color.red);
        lbl_confirmarDataReserva.setVisible(false);
        lbl_confirmarDataReserva.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_lancarreserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_lancarreserva = new javax.swing.JTable();
        lbl_cliente = new javax.swing.JLabel();
        btn_consultarcliente = new javax.swing.JButton();
        txt_cliente = new javax.swing.JTextField();
        btn_consultaproduto = new javax.swing.JButton();
        lbl_produto = new javax.swing.JLabel();
        txt_produto = new javax.swing.JTextField();
        txt_datareserva = new javax.swing.JTextField();
        lbl_datareserva = new javax.swing.JLabel();
        lbl_datalcto = new javax.swing.JLabel();
        txt_datalcto = new javax.swing.JTextField();
        btn_sair = new javax.swing.JButton();
        btn_confirmar = new javax.swing.JButton();
        lbl_confirmarDataReserva = new javax.swing.JLabel();
        lbl_confirmarDataLcto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_lancarreserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_lancarreserva.setText("Lançar Reserva");

        table_lancarreserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Valor", "Quantidade ", "Autor", "DtaLcto", "Volume", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(table_lancarreserva);

        lbl_cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cliente.setText("Cliente");

        btn_consultarcliente.setText("Consultar Cliente");

        btn_consultaproduto.setText("Consultar Produto");

        lbl_produto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_produto.setText("Produto");

        lbl_datareserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_datareserva.setText("Data Reserva");

        lbl_datalcto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_datalcto.setText("Data Lcto");

        btn_sair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sair.setText("Sair");

        btn_confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_confirmar.setText("Confirmar");
        btn_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmarMouseClicked(evt);
            }
        });

        lbl_confirmarDataReserva.setText("*");

        lbl_confirmarDataLcto.setText("*");

        jLabel1.setText("*campos obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_produto)
                                .addGap(40, 40, 40)
                                .addComponent(txt_produto))
                            .addComponent(lbl_lancarreserva, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cliente)
                                    .addComponent(lbl_datareserva)
                                    .addComponent(lbl_datalcto))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cliente)
                                    .addComponent(txt_datareserva)
                                    .addComponent(txt_datalcto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_consultaproduto)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_consultarcliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_confirmar)
                                                .addGap(32, 32, 32)
                                                .addComponent(btn_sair))))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_confirmarDataReserva)
                                    .addComponent(lbl_confirmarDataLcto))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lancarreserva)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cliente)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultarcliente)
                    .addComponent(btn_sair)
                    .addComponent(btn_confirmar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_datareserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_datareserva)
                    .addComponent(lbl_confirmarDataReserva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_datalcto)
                    .addComponent(txt_datalcto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_confirmarDataLcto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consultaproduto)
                    .addComponent(lbl_produto)
                    .addComponent(txt_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmarMouseClicked
        // TODO add your handling code here:
        
        if(txt_datalcto.getText().length() > 0)
        {
            lbl_confirmarDataLcto.setVisible(false);
        }
        else
        {
            lbl_confirmarDataLcto.setVisible(true);
        }
        
        if(txt_datareserva.getText().length() > 0 )
        {
            lbl_confirmarDataReserva.setVisible(false);
        }
        else{
            lbl_confirmarDataReserva.setVisible(true);
        }
        
        if(txt_datalcto.getText().length() > 0 &&
                txt_datareserva.getText().length() > 0 )
        {
            JOptionPane.showMessageDialog(null, "Cadastro Feito com sucesso");
        }
    }//GEN-LAST:event_btn_confirmarMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_consultaproduto;
    private javax.swing.JButton btn_consultarcliente;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JLabel lbl_confirmarDataLcto;
    private javax.swing.JLabel lbl_confirmarDataReserva;
    private javax.swing.JLabel lbl_datalcto;
    private javax.swing.JLabel lbl_datareserva;
    private javax.swing.JLabel lbl_lancarreserva;
    private javax.swing.JLabel lbl_produto;
    private javax.swing.JTable table_lancarreserva;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_datalcto;
    private javax.swing.JTextField txt_datareserva;
    private javax.swing.JTextField txt_produto;
    // End of variables declaration//GEN-END:variables
}
