package triforce;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author angelo
 */
public class Cadastrar_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_Pedido
     */
    public Cadastrar_Pedido() {
        initComponents();
        lbl_confirmar_dlcto.setVisible(false);
        lbl_confirmar_dlcto.setForeground(Color.red);
        lbl_confirmar_dreserva.setVisible(false);
        lbl_confirmar_dreserva.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_Pedido = new javax.swing.JLabel();
        lbl_Produto = new javax.swing.JLabel();
        txt_Produto = new javax.swing.JTextField();
        btn_Produto = new javax.swing.JButton();
        lbl_Lcto = new javax.swing.JLabel();
        txt_Lcto = new javax.swing.JTextField();
        lbl_Previsao = new javax.swing.JLabel();
        txt_Previsao = new javax.swing.JTextField();
        Fornecedor = new javax.swing.JLabel();
        txt_Fornecedor = new javax.swing.JTextField();
        btn_Fornecedor = new javax.swing.JButton();
        btn_Voltar = new javax.swing.JButton();
        btn_Confirmar = new javax.swing.JButton();
        chk_Baixado = new javax.swing.JCheckBox();
        lbl_confirmar_dlcto = new javax.swing.JLabel();
        lbl_confirmar_dreserva = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Volume", "Autor", "Data Lcto", "Categoria", "Preço", "Saldo", "Qtd"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbl_Pedido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Pedido.setText("Cadastrar Pedido");

        lbl_Produto.setText("Produto:");

        btn_Produto.setText("Consultar Produto");

        lbl_Lcto.setText("Data Lcto:");

        lbl_Previsao.setText("Data Reserva:");

        Fornecedor.setText("Fornecedor:");

        btn_Fornecedor.setText("Consultar Fornecedor");

        btn_Voltar.setText("Voltar");

        btn_Confirmar.setText("Confirmar");
        btn_Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConfirmarMouseClicked(evt);
            }
        });

        chk_Baixado.setText("Baixado");

        lbl_confirmar_dlcto.setText("*");

        lbl_confirmar_dreserva.setText("*");

        jLabel1.setText("*campos obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Pedido)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Produto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Produto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Produto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Previsao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Previsao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Lcto)
                                .addGap(30, 30, 30)
                                .addComponent(txt_Lcto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_confirmar_dlcto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Confirmar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Voltar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Fornecedor)
                                            .addComponent(lbl_confirmar_dreserva))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(219, 219, 219))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_Baixado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Pedido)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Lcto)
                    .addComponent(txt_Lcto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Voltar)
                    .addComponent(btn_Confirmar)
                    .addComponent(lbl_confirmar_dlcto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Previsao)
                    .addComponent(txt_Previsao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_confirmar_dreserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fornecedor)
                    .addComponent(txt_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Fornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_Baixado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Produto)
                    .addComponent(txt_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Produto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfirmarMouseClicked
        // TODO add your handling code here:
        if(txt_Lcto.getText().length() > 0)
        {
            lbl_confirmar_dlcto.setVisible(false);
        }
        else
        {
            lbl_confirmar_dlcto.setVisible(true);
        }
        
        if(txt_Previsao.getText().length() > 0 )
        {
            lbl_confirmar_dreserva.setVisible(false);
        }
        else{
            lbl_confirmar_dreserva.setVisible(true);
        }
        
        if(txt_Lcto.getText().length() > 0 &&
                txt_Previsao.getText().length() > 0 )
        {
            JOptionPane.showMessageDialog(null, "Cadastro Feito com sucesso");
        }
    }//GEN-LAST:event_btn_ConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fornecedor;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JButton btn_Fornecedor;
    private javax.swing.JButton btn_Produto;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JCheckBox chk_Baixado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Lcto;
    private javax.swing.JLabel lbl_Pedido;
    private javax.swing.JLabel lbl_Previsao;
    private javax.swing.JLabel lbl_Produto;
    private javax.swing.JLabel lbl_confirmar_dlcto;
    private javax.swing.JLabel lbl_confirmar_dreserva;
    private javax.swing.JTextField txt_Fornecedor;
    private javax.swing.JTextField txt_Lcto;
    private javax.swing.JTextField txt_Previsao;
    private javax.swing.JTextField txt_Produto;
    // End of variables declaration//GEN-END:variables
}
