package triforce;


import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a145292
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
        lbl_confirmarRazaosocial.setVisible(false);
        lbl_confirmarRazaosocial.setForeground(Color.red);
        lbl_confirmarNomeFantasia.setVisible(false);
        lbl_confirmarNomeFantasia.setForeground(Color.red);
        lbl_confirmarCnpj.setVisible(false);
        lbl_confirmarCnpj.setForeground(Color.red);
        lbl_confirmarTelefone.setVisible(false);
        lbl_confirmarTelefone.setForeground(Color.red);
        lbl_confirmarEmail.setVisible(false);
        lbl_confirmarEmail.setForeground(Color.red);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadastrofornecedor = new javax.swing.JLabel();
        lbl_razaosocial = new javax.swing.JLabel();
        lbl_nomefantasia = new javax.swing.JLabel();
        lbl_cnpj = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        txt_razaosocial = new javax.swing.JTextField();
        txt_nomefantasia = new javax.swing.JTextField();
        txt_cnpj = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        btn_gravar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        lbl_confirmarRazaosocial = new javax.swing.JLabel();
        lbl_confirmarNomeFantasia = new javax.swing.JLabel();
        lbl_confirmarCnpj = new javax.swing.JLabel();
        lbl_confirmarTelefone = new javax.swing.JLabel();
        lbl_confirmarEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_cadastrofornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cadastrofornecedor.setText("Cadastro Fornecedor");

        lbl_razaosocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_razaosocial.setText("Razão social");

        lbl_nomefantasia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nomefantasia.setText("Nome fantasia");

        lbl_cnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cnpj.setText("CNPJ");

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_email.setText("Email");

        lbl_telefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_telefone.setText("Telefone");

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        btn_gravar.setText("Gravar");
        btn_gravar.setActionCommand("Salvar");
        btn_gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gravarMouseClicked(evt);
            }
        });

        btn_voltar.setText("Voltar");

        lbl_confirmarRazaosocial.setText("*");

        lbl_confirmarNomeFantasia.setText("*");

        lbl_confirmarCnpj.setText("*");

        lbl_confirmarTelefone.setText("*");

        lbl_confirmarEmail.setText("*");

        jLabel1.setText("*campos obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_razaosocial)
                                    .addComponent(lbl_telefone)
                                    .addComponent(lbl_email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_gravar)
                                        .addGap(80, 80, 80)
                                        .addComponent(btn_voltar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_razaosocial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_telefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_nomefantasia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nomefantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_cnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_confirmarTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_confirmarEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_confirmarCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_confirmarNomeFantasia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_confirmarRazaosocial)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lbl_cadastrofornecedor)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_cadastrofornecedor)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_razaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_razaosocial)
                    .addComponent(lbl_confirmarRazaosocial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomefantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nomefantasia)
                    .addComponent(lbl_confirmarNomeFantasia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cnpj)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_confirmarCnpj)
                            .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefone)
                    .addComponent(lbl_confirmarTelefone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email)
                    .addComponent(lbl_confirmarEmail))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gravar)
                    .addComponent(btn_voltar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_gravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gravarMouseClicked
        // TODO add your handling code here:
        if(txt_razaosocial.getText().length() > 0 ){
            lbl_confirmarRazaosocial.setVisible(false);
        }else 
        {
            lbl_confirmarRazaosocial.setVisible(true);
        }
        if(txt_nomefantasia.getText().length() > 0 )
        {
            lbl_confirmarNomeFantasia.setVisible(false);
        }else
        {
            lbl_confirmarNomeFantasia.setVisible(true);
        }
        if(txt_cnpj.getText().length() > 0){
            lbl_confirmarCnpj.setVisible(false);
        }else 
        {
            lbl_confirmarCnpj.setVisible(true);
        }
        if (txt_telefone.getText().length() > 0 )
        {
            lbl_confirmarTelefone.setVisible(false);
        }else{
            lbl_confirmarTelefone.setVisible(true);
        }
        if(txt_email.getText().length() > 0 )
        {
            lbl_confirmarEmail.setVisible(false);
        }else
        {
            lbl_confirmarEmail.setVisible(true);
        }
         if(txt_razaosocial.getText().length() > 0 
                 &&txt_nomefantasia.getText().length() > 0 
                 &&txt_cnpj.getText().length() > 0 
                 &&txt_telefone.getText().length() > 0
                 &&txt_email.getText().length() > 0){
             JOptionPane.showMessageDialog(null, "Dados Cadastrados com sucesso");
         }
    }//GEN-LAST:event_btn_gravarMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cadastrofornecedor;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_confirmarCnpj;
    private javax.swing.JLabel lbl_confirmarEmail;
    private javax.swing.JLabel lbl_confirmarNomeFantasia;
    private javax.swing.JLabel lbl_confirmarRazaosocial;
    private javax.swing.JLabel lbl_confirmarTelefone;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nomefantasia;
    private javax.swing.JLabel lbl_razaosocial;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_cnpj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nomefantasia;
    private javax.swing.JTextField txt_razaosocial;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
