package triforce;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author l147033
 */
public class Controle_Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Estoque
     */
    public Controle_Estoque() {
        initComponents();
        lbl_confirmar_consulta.setVisible(false);
        lbl_confirmar_consulta.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_estoque = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        txt_consultar = new javax.swing.JTextField();
        btn_confirmar = new javax.swing.JButton();
        rad_adicionar = new javax.swing.JRadioButton();
        rad_remover = new javax.swing.JRadioButton();
        lbl_confirmar_consulta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Controle Estoque");

        btn_consultar.setText("Consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });

        tab_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Volume", "Autor", "Data_Lançamento", "Categoria", "Preço", "Saldo", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tab_estoque);

        jButton5.setText("Voltar");

        btn_confirmar.setText("Confirmar");

        buttonGroup1.add(rad_adicionar);
        rad_adicionar.setText("Adicionar");

        buttonGroup1.add(rad_remover);
        rad_remover.setText("Remover");

        lbl_confirmar_consulta.setText("*");

        jLabel2.setText("*campos obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(207, 207, 207))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lbl_confirmar_consulta)
                        .addGap(7, 7, 7)
                        .addComponent(btn_consultar)
                        .addGap(86, 86, 86)
                        .addComponent(rad_adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad_remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consultar)
                    .addComponent(jButton5)
                    .addComponent(txt_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmar)
                    .addComponent(rad_adicionar)
                    .addComponent(rad_remover)
                    .addComponent(lbl_confirmar_consulta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        // TODO add your handling code here:
        if (txt_consultar.getText().length() > 0)
        {
            lbl_confirmar_consulta.setVisible(false);
            
        }else
        {
            lbl_confirmar_consulta.setVisible(true);
            
        }
        if(txt_consultar.getText().length() > 0)          
        {
        JOptionPane.showMessageDialog(null, "Dados cadastrados com Sucesso");        
        }
        else{
       // JOptionPane.showMessageDialog(null, "Favor validar" );
        }
    }//GEN-LAST:event_btn_consultarMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_confirmar_consulta;
    private javax.swing.JRadioButton rad_adicionar;
    private javax.swing.JRadioButton rad_remover;
    private javax.swing.JTable tab_estoque;
    private javax.swing.JTextField txt_consultar;
    // End of variables declaration//GEN-END:variables
}
