/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triforce;

/**
 *
 * @author angelo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar_Principal = new javax.swing.JMenuBar();
        op_Arquivos = new javax.swing.JMenu();
        op_Cadastros = new javax.swing.JMenu();
        op_Produtos = new javax.swing.JMenuItem();
        op_Funcionarios = new javax.swing.JMenuItem();
        op_Cliente = new javax.swing.JMenuItem();
        op_Fornecedor = new javax.swing.JMenuItem();
        op_Acoes = new javax.swing.JMenu();
        op_Venda = new javax.swing.JMenuItem();
        op_Reserva = new javax.swing.JMenuItem();
        op_Pedido = new javax.swing.JMenuItem();
        op_Estoque = new javax.swing.JMenuItem();
        op_Info = new javax.swing.JMenu();
        op_Caixa = new javax.swing.JMenuItem();
        op_Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        op_Arquivos.setText("Arquivos");

        op_Cadastros.setText("Cadastros");

        op_Produtos.setText("Produtos");
        op_Cadastros.add(op_Produtos);

        op_Funcionarios.setText("Funcionários");
        op_Cadastros.add(op_Funcionarios);

        op_Cliente.setText("Cliente");
        op_Cadastros.add(op_Cliente);

        op_Fornecedor.setText("Fornecedor");
        op_Cadastros.add(op_Fornecedor);

        op_Arquivos.add(op_Cadastros);

        bar_Principal.add(op_Arquivos);

        op_Acoes.setText("Ações");

        op_Venda.setText("Realizar Venda");
        op_Acoes.add(op_Venda);

        op_Reserva.setText("Reservas");
        op_Acoes.add(op_Reserva);

        op_Pedido.setText("Pedido de Compra");
        op_Acoes.add(op_Pedido);

        op_Estoque.setText("Estoque");
        op_Acoes.add(op_Estoque);

        bar_Principal.add(op_Acoes);

        op_Info.setText("Info");

        op_Caixa.setText("Fluxo de Caixa");
        op_Info.add(op_Caixa);

        bar_Principal.add(op_Info);

        op_Sair.setText("Sair");
        bar_Principal.add(op_Sair);

        setJMenuBar(bar_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bar_Principal;
    private javax.swing.JMenu op_Acoes;
    private javax.swing.JMenu op_Arquivos;
    private javax.swing.JMenu op_Cadastros;
    private javax.swing.JMenuItem op_Caixa;
    private javax.swing.JMenuItem op_Cliente;
    private javax.swing.JMenuItem op_Estoque;
    private javax.swing.JMenuItem op_Fornecedor;
    private javax.swing.JMenuItem op_Funcionarios;
    private javax.swing.JMenu op_Info;
    private javax.swing.JMenuItem op_Pedido;
    private javax.swing.JMenuItem op_Produtos;
    private javax.swing.JMenuItem op_Reserva;
    private javax.swing.JMenu op_Sair;
    private javax.swing.JMenuItem op_Venda;
    // End of variables declaration//GEN-END:variables
}
